# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bef59a773afbbf06f174f72dd562806b05b1daadc088bbd557f5d37f564b2d513a8e3fb35c8afce29360ee0fbebc0d95bc2b9e55e4b2ab49e799e61db8d2e091

test:
  secret_key_base: 2533b73753547308f89675b820538a4a7e1b5430e22345bc5956503efb0c5a0b17d285a70ea20c4bbc46e296d94ca69a5b4beeef1e6f6d5d05dfe55f0721ae89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
